In [22]:
import numpy as np

In [23]:
a = np.arange(12).reshape(3,4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
#this is a C ORDER
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
#this is FORTRAN ORDER
#nditer function allows you to do iteration in variety of ways
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [12]:
for x in np.nditer(a,order='F',flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [24]:
#lets modify the original array
#print the square of each elemets
for x in np.nditer(a,op_flags= ['readwrite']):
    x[...]=x*x

In [25]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [28]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [31]:
#it will generate 10 linearly spaced nos. between 1 and 5
a=np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
a.sum()

30.0

In [35]:
a.min()

1.0

In [36]:
a.max()

5.0

In [38]:
#it tells the data type 
a.dtype

dtype('float64')

In [39]:
#now lets use vstack and hstack for that we have to create two arrays
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [40]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
np.hstack((a,b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])